const JassFuncBuilder = require('.')
const j = new JassFuncBuilder()
j.setIndentBase(4)
j.setIndent(4)
j.setName('CreateFooAwesomeUnit')
j.setPrefix('public')
j.setReturnType('unit')
j.addParam('player', 'plr')
j.addParam('unit', 'owner')
j.addParam('location', 'birthLoc')
j.addAction(`CreateUnitAtLoc(plr, owner, GetLocationX(birthLoc), GetLocationY(birthLoc));`)
j.addAction(`TemporaryRemoveLocation(birthLoc);`)
console.log(j.build())
